=== isi-usc-edu/qb-gsee-benchmark/schemas/performance_metrics.schema.0.0.1.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "performance_metrics.schema.0.0.1.json",
    "title": "Quantum Benchmarking Performance Metrics File Schema",
    "description": "Describes required fields for a valid performance metrics file.",
    "required": [
        "performance_metrics_uuid",
        "solver_short_name",
        "solver_uuid",
        "creation_timestamp",
        "ml_metrics",
        "top_level_results",
        "results_by_problem_instance",
        "results_by_task",
        "$schema"
    ],
    "properties": {
        "$schema": {
            "title": "Schema URI",
            "desription": "A hyperlink to the schema that describes this JSON object.",
            "type": "string"
        },
        "performance_metrics_uuid": {
            "title": "Performance Metrics UUID",
            "description": "The UUID of the performance metrics file as a string in 8-4-4-4-12 format.",
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        },
        "creation_timestamp": {
            "title": "Creation Timestamp",
            "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
            "type": "string",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
        },
        "solver_short_name": {
            "title": "Short name of the solver.",
            "description": "A short string for human readability that is not necessarily unique.  E.g., `DMRG_32core_64GB`",
            "type": "string"
        },
        "solver_uuid": {
            "title": "The UUID of the solver.",
            "description": "The UUID of the solver as a string in 8-4-4-4-12 format.",
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        },
        "ml_metrics": {
            "title": "ML performance metrics",
            "description": "TODO",
            "type": "object",
            "required": [
                "solvability_ratio",
                "f1_score"
            ],
            "properties": {
                "ml_metrics_calculator_version": {
                    "title": "ML performance metrics calculator version",
                    "description": "The version of the ML metrics calculator software.",
                    "type": "number"
                },
                "solvability_ratio": {
                    "title": "ML Solvability Ratio",
                    "description": "TODO.  A number between 0-1.  A higher number is better.",
                    "type":["null","number"]
                },
                "f1_score": {
                    "title": "F1 score",
                    "description": "TODO.  This is a measure of the goodness of the ML model, not the solver being evaluated.",
                    "type": ["null","array"]
                }
            }
        },
        "top_level_results":{
            "title": "Results",
            "description": "Aggregated performance metrics and ML scores.",
            "type": "object",
            "required":[
                "number_of_problem_instances",
                "number_of_problem_instances_attempted",
                "number_of_problem_instances_solved",
                "number_of_tasks",
                "number_of_tasks_attempted",
                "number_of_tasks_solved",
                "number_of_tasks_solved_within_run_time_limit",
                "number_of_tasks_solved_within_accuracy_threshold",
                "max_run_time_of_attempted_tasks",
                "sum_of_run_time_of_attempted_tasks"
            ],
            "properties":{
                "number_of_problem_instances":{
                    "title": "Number of problem instances available.",
                    "description": "A count of the number of `problem_instances` currently available (at creation time of this file) in the `problem_instances` directory.",
                    "type": "integer"
                },
                "number_of_problem_instances_attempted":{
                    "title": "Number of problem instances attempted",
                    "description": "A count of the number of `problem_instances` where a solution was provided for at least one Hamiltonian (task) in the `problem_instance`",
                    "type": "integer"
                },
                "number_of_problem_instances_solved":{
                    "title": "Number of problem instances solved",
                    "description": "A count of the number of `problem_instances` where the solutions for *all* Hamiltonians (tasks) were within the run time and accuracy requirements.",
                    "type": "integer"
                },
                "number_of_tasks":{
                    "title": "Number of Hamiltonians (tasks) available.",
                    "description": "A count of the number of Hamiltonians (tasks) currently available (at creation time of this file) required in each `problem_instance` file.",
                    "type": "integer"
                },
                "number_of_tasks_attempted":{
                    "title": "Number of Hamiltonians (tasks) attempted.",
                    "description": "A count of the number of Hamiltonians (tasks) where a solution was provided.",
                    "type": "integer"
                },
                "number_of_tasks_solved_within_run_time_limit":{
                    "title": "Number of Hamiltonians (tasks) solved within run time limit.",
                    "description": "A count of the number of Hamiltonians (tasks) where a solution was provided that was within the run time limit.",
                    "type": "integer"
                },
                "number_of_tasks_solved_within_accuracy_threshold":{
                    "title": "Number of Hamiltonians (tasks) solved within accuracy threshold.",
                    "description": "A count of the number of Hamiltonians (tasks) where a solution was provided that was within the accuracy threshold.",
                    "type": "integer"
                },
                "number_of_tasks_solved":{
                    "title": "Number of Hamiltonians (tasks) solved to requirements.",
                    "description": "A count of the number of Hamiltonians (tasks) where a solution was provided met requirements.",
                    "type": "integer"
                },
                "max_run_time_of_attempted_tasks":{
                    "title": "Max run time of attempted Hamiltonians (tasks).",
                    "description": "The maximum run time of the solutions provided for all attempted Hamiltonians (tasks).  In seconds.",
                    "type": "number"
                },
                "sum_of_run_time_of_attempted_tasks":{
                    "title": "The sum of the run time of attempted Hamiltonians (tasks).",
                    "description": "The sum of the run time of the solutions provided for all attempted Hamiltonians (tasks).  In seconds.",
                    "type": "number"
                }
            }
        },
        "results_by_problem_instance":{
            "title": "Results aggregated by problem instance",
            "description": "Performance metrics are aggregated to the `problem_instance` level.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "problem_instance_uuid",
                    "solution_uuid",
                    "number_of_tasks",
                    "number_of_tasks_attempted",
                    "number_of_tasks_solved_within_runtime_limit",
                    "number_of_tasks_solved_within_accuracy_requirement",
                    "number_of_tasks_solved",
                    "sum_of_run_time_of_attempted_tasks",
                    "max_run_time_of_attempted_tasks",
                    "solution_submitted_by_due_date"
                ],
                "properties": {
                    "problem_instance_uuid": {
                        "title": "Problem instance UUID",
                        "description": "The UUID of the starting `problem_instance`.  A string in 8-4-4-4-12 format.",
                        "type": "string",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    },
                    "solution_uuid": {
                        "title": "Solution file UUID",
                        "description": "The UUID of the solution JSON submitted by a performer/solver to solve the associated `problem_instance`.  A string in 8-4-4-4-12 format.",
                        "type": ["null","string"],
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    },
                    "number_of_tasks_attempted": {
                        "type": "integer",
                        "description": "TODO DESCRIPTION"
                    },
                    "number_of_tasks_solved_within_runtime_limit": {
                        "type": "integer",
                        "description": "TODO DESCRIPTION"
                    },
                    "hamiltonians_solved_within_accuracy_requirement": {
                        "type": "integer",
                        "description": "TODO DESCRIPTION"
                    },
                    "number_of_tasks_solved": {
                        "type": "integer",
                        "description": "TODO DESCRIPTION solved within run time limit and accuracy threshold."
                    },
                    "number_of_tasks": {
                        "type": "integer",
                        "description": "TODO DESCRIPTION"
                    },
                    "sum_of_run_time_of_attempted_tasks": {
                        "type": ["null","number"],
                        "description": "TODO DESCRIPTION."
                    },
                    "max_of_run_time_of_attempted_tasks": {
                        "type": ["null","number"],
                        "description": "TODO DESCRIPTION."
                    },
                    "solution_submitted_by_due_date": {
                        "title": "Solution Within Due Date?",
                        "description": "Each `problem_instance` file has a specified calendar due date.  This boolean to identifies if the solution was submitted by the due date.  If there was no due date specified, then this is `true`.",
                        "type": ["null","boolean"]
                    }
                }
            }
        },
        "results_by_task": {
            "title": "TODO",
            "description": "A list of objects, one for each Hamiltonian (by `task_uuid`)",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "task_uuid",
                    "problem_instance_uuid",
                    "instance_data_object_uuid",
                    "attempted",
                    "solved_within_run_time",
                    "solved_within_accuracy_requirement",
                    "overall_run_time_seconds"
                ],
                "properties": {
                    "task_uuid": {
                        "title": "Task UUID",
                        "description": "UUID for the task from the list of tasks in the `problem_instance` file in 8-4-4-4-12 format.",
                        "type": "string",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    },
                    "problem_instance_uuid": {
                        "title": "Problem instance UUID",
                        "description": "The UUID of the starting `problem_instance`.  A string in 8-4-4-4-12 format.",
                        "type": "string",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    },
                    "instance_data_object_uuid": {
                        "title": "Instance Data Object UUID",
                        "description": "UUID for the data object (typically a Hamiltonian in FCIDUMP format) in 8-4-4-4-12 format.",
                        "type": "string",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    },
                    "attempted": {
                        "title": "TODO",
                        "description": "a boolean indicating if the solver attempted to calculate the GSE for the Hamiltonian.  At this time, if the data is missing from `solution.json` files, it is considered NOT attempted and other metrics indicate failure.",
                        "type": "boolean"
                    },
                    "solved_within_run_time": {
                        "title": "TODO",
                        "description": "a boolean indicating if the solver run time was within the run time requirement specified in the problem_instance.",
                        "type": ["null","boolean"]
                    },
                    "solved_within_accuracy_requirement": {
                        "title": "TODO",
                        "description": "a boolean indicating if the solver run time was within the accuracy requirement specified in the problem_instance.",
                        "type": ["null","boolean"]
                    },
                    "overall_run_time_seconds":{
                        "title": "TODO",
                        "description": "TODO",
                        "type": ["null", "number"]
                    }
                }
            }
        }
    }
}

=== isi-usc-edu/qb-gsee-benchmark/performance_metrics/performance_metrics.DF_QPE.5d768520-b3d0-4292-bbb4-9776fa128107.json
{
    "$schema": "https://raw.githubusercontent.com/isi-usc-edu/qb-gsee-benchmark/main/schemas/performance_metrics.schema.0.0.1.json",
    "performance_metrics_uuid": "081f384b-cdcd-42de-8dc7-5117b0876996",
    "solver_short_name": "DF_QPE",
    "solver_uuid": "5d768520-b3d0-4292-bbb4-9776fa128107",
    "creation_timestamp": "2026-04-07T11:49:13.945074+00:00",
    "ml_metrics": {
        "solvability_ratio": 0.0394,
        "comments": "solvability ratio based on PCA embedding.",
        "f1_score": [
            1.0,
            1.0
        ],
        "ml_metrics_calculator_version": 1
    },
    "top_level_results": {
        "number_of_problem_instances": 68,
        "number_of_problem_instances_attempted": 24,
        "number_of_problem_instances_solved": 2,
        "number_of_tasks": 228,
        "number_of_tasks_attempted": 137,
        "number_of_tasks_solved": 2,
        "number_of_tasks_solved_within_run_time_limit": 2,
        "number_of_tasks_solved_within_accuracy_threshold": 137,
        "max_run_time_of_attempted_tasks": 71881480309304.23,
        "sum_of_run_time_of_attempted_tasks": 92303779438561.5
    },
    "results_by_problem_instance": [
        {
            "problem_instance_uuid": "dc8bdc56-5ebd-4996-6b81-81b1a06d8c76",
            "solution_uuid": "70019442-e381-40c5-b5d0-a9a2f155ee1e",
            "number_of_tasks": 12,
            "number_of_tasks_attempted": 12,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 12,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 1071622854449.7314,
            "max_run_time_of_attempted_tasks": 505208801839.9823,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "766ba2da-e72a-4e03-a739-f97269026fc4",
            "solution_uuid": "420d66c0-8ce2-4df9-ba02-c7a6a3f25ea2",
            "number_of_tasks": 1,
            "number_of_tasks_attempted": 1,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 1,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 201417693.350765,
            "max_run_time_of_attempted_tasks": 201417693.350765,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "664ec8e4-09d5-41cc-6266-ddb26219366f",
            "solution_uuid": "d02728c0-fd80-45ab-bc2b-071acc937166",
            "number_of_tasks": 4,
            "number_of_tasks_attempted": 4,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 4,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 12927341361.316359,
            "max_run_time_of_attempted_tasks": 5230897378.991123,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "614c4444-a31a-4348-b24d-01040208651c",
            "solution_uuid": null,
            "number_of_tasks": 30,
            "number_of_tasks_attempted": 0,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 0,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": null,
            "max_run_time_of_attempted_tasks": null,
            "solution_submitted_by_due_date": false
        },
        {
            "problem_instance_uuid": "3f141f05-532b-478d-b38a-2ae07baadc88",
            "solution_uuid": "d1ca05b7-ef02-4b30-bfe5-4872e26b85d3",
            "number_of_tasks": 3,
            "number_of_tasks_attempted": 2,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 2,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 8666088673.070866,
            "max_run_time_of_attempted_tasks": 8263644415.001101,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "1c3155e0-3679-4eff-bed0-57a1082672c3",
            "solution_uuid": "bd630d73-2bda-41d6-8537-762939fd2bc5",
            "number_of_tasks": 3,
            "number_of_tasks_attempted": 2,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 2,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 1296506224074.1013,
            "max_run_time_of_attempted_tasks": 1286927597226.498,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "a8895776-3583-4884-fbc7-d6f9df21a7ac",
            "solution_uuid": "0364de32-21b8-465d-8286-bfc8e9b7eedd",
            "number_of_tasks": 9,
            "number_of_tasks_attempted": 9,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 9,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 41923036592.73371,
            "max_run_time_of_attempted_tasks": 7133916866.2664385,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "e48e7467-1fcd-478b-a599-f4ce881c57b9",
            "solution_uuid": null,
            "number_of_tasks": 3,
            "number_of_tasks_attempted": 2,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 2,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 5511024660.096926,
            "max_run_time_of_attempted_tasks": 5306292912.596156,
            "solution_submitted_by_due_date": false
        },
        {
            "problem_instance_uuid": "c2009f9f-4738-4919-9295-5f9231ca5199",
            "solution_uuid": null,
            "number_of_tasks": 16,
            "number_of_tasks_attempted": 0,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 0,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": null,
            "max_run_time_of_attempted_tasks": null,
            "solution_submitted_by_due_date": false
        },
        {
            "problem_instance_uuid": "2e61ba35-b6b0-42b5-b3e8-d25bd83145ba",
            "solution_uuid": "3c4adbae-2248-47e8-93c0-d39d0a4a932a",
            "number_of_tasks": 3,
            "number_of_tasks_attempted": 2,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 2,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 925027475677.9215,
            "max_run_time_of_attempted_tasks": 843856528253.3472,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "8a3787cc-d3d0-42a8-d9a9-7de2aed45208",
            "solution_uuid": "5e4afee4-3169-4337-8c9b-48e5892df995",
            "number_of_tasks": 16,
            "number_of_tasks_attempted": 16,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 16,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 14083631394238.574,
            "max_run_time_of_attempted_tasks": 7234554349266.43,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "c1e4c7dd-2dc4-4dd0-889d-fb34f602965a",
            "solution_uuid": null,
            "number_of_tasks": 2,
            "number_of_tasks_attempted": 1,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 1,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 659000639491.4393,
            "max_run_time_of_attempted_tasks": 659000639491.4393,
            "solution_submitted_by_due_date": false
        },
        {
            "problem_instance_uuid": "00043d56-ed63-4266-907c-99c95c51b9db",
            "solution_uuid": "894d6ff2-e581-49f1-bf9d-7ca6b087fc52",
            "number_of_tasks": 1,
            "number_of_tasks_attempted": 1,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 1,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 71881480309304.23,
            "max_run_time_of_attempted_tasks": 71881480309304.23,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "a14a1e28-71c5-4e23-bf6e-dd9662a6df58",
            "solution_uuid": "7fd61f5c-9ef8-4561-a70f-002442003ca4",
            "number_of_tasks": 2,
            "number_of_tasks_attempted": 1,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 1,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 137174245097.45984,
            "max_run_time_of_attempted_tasks": 137174245097.45984,
            "solution_submitted_by_due_date": true
        },
        {
            "problem_instance_uuid": "1448d27d-bfa9-470f-a6c8-864a295b66f4",
            "solution_uuid": null,
            "number_of_tasks": 2,
            "number_of_tasks_attempted": 1,
            "number_of_tasks_solved_within_runtime_limit": 0,
            "number_of_tasks_solved_within_accuracy_requirement": 1,
            "number_of_tasks_solved": 0,
            "sum_of_run_time_of_attempted_tasks": 241839333327.2801,
            "max_run_time_of_attempted_tasks": 241839333327.2801,
